name: hmb_tooltip
description: A Custom Tooltip component
homepage: https://github.com/moweiran/hmb_tooltip
version: 0.0.5
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.1
  flutter: ">=3.13.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter

  flutter_animate: ^4.1.1+1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
